TOP=..
include $(TOP)/configure/CONFIG
#=======================================

# Install .dbd and .db files
DB += prltherm.db
DATA += prltherm.proto

#=======================================
include $(TOP)/configure/RULES
