TOP=..
include $(TOP)/configure/CONFIG
#=======================================

# Install .dbd and .db files
DB += prltherm.db
# DBD += prltherm.dbd

#=======================================
include $(TOP)/configure/RULES
